# Binary Logistic Regression

In [48]:
import numpy as np
import pandas as pd
import statsmodels
import sklearn
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [49]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='mtcars')

In [50]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [51]:
df = df[['hp','wt','am']]
df.head()

hp     wt  am
0  110  2.620   1
1  110  2.875   1
2   93  2.320   1
3  110  3.215   0
4  175  3.440   0

- am - binary data
- hp and wt - continuous data

In [52]:
x_train = df.drop('am',axis = 1)

In [53]:
y_train = df.am

In [54]:
x_train = sm.add_constant(x_train,prepend=False)

In [55]:
mod1 = sm.Logit(y_train,x_train).fit()

Optimization terminated successfully.
         Current function value: 0.157174
         Iterations 9


In [56]:
print(mod1.summary())

                           Logit Regression Results                           
Dep. Variable:                     am   No. Observations:                   32
Model:                          Logit   Df Residuals:                       29
Method:                           MLE   Df Model:                            2
Date:                Thu, 22 Jun 2023   Pseudo R-squ.:                  0.7673
Time:                        22:46:46   Log-Likelihood:                -5.0296
converged:                       True   LL-Null:                       -21.615
Covariance Type:            nonrobust   LLR p-value:                 6.267e-08
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
hp             0.0363      0.018      2.044      0.041       0.001       0.071
wt            -8.0835      3.069     -2.634      0.008     -14.098      -2.069
const         18.8663      7.444      2.535      0.0

In [57]:
x_train.head()

hp     wt  const
0  110  2.620    1.0
1  110  2.875    1.0
2   93  2.320    1.0
3  110  3.215    1.0
4  175  3.440    1.0

In [58]:
mydata = pd.DataFrame([[120,2,1],[120,2.5,1],[120,3,1]],columns=['hp','wt','const'])

In [59]:
mod1.predict(mydata)

0    0.999133
1    0.952947
2    0.262415
dtype: float64

In [60]:
#calculation for wt
np.log(0.999133/(1-0.999133)) - np.log(0.262415/(1-0.262415))

8.083058320861667

# EXERCISE / Another Example

- cyl as predictor - num of selectors, but assume it as categorical, chnage in the type of cyl will have any influnce on

In [18]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='diabetes')

In [19]:
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             72             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3       89             66             23       94  28.1   
4      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                      0.63   50        1  
1                      0.35   31        0  
2                      0.67   32        1  
3                      0.17   21        0  
4                      2.29   33        1

In [20]:
df = df[['Glucose','BloodPressure','Age','Outcome']]

In [21]:
df.head()

Glucose  BloodPressure  Age  Outcome
0      148             72   50        1
1       85             66   31        0
2      183             64   32        1
3       89             66   21        0
4      137             40   33        1

In [22]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Outcome',axis=1),df['Outcome'],test_size=0.25)

In [23]:
x_train = sm.add_constant(x_train, prepend=False)

In [24]:
mod1 = sm.Logit(y_train,x_train).fit()

Optimization terminated successfully.
         Current function value: 0.528636
         Iterations 6


In [25]:
print(mod1.summary())

                           Logit Regression Results                           
Dep. Variable:                Outcome   No. Observations:                  576
Model:                          Logit   Df Residuals:                      572
Method:                           MLE   Df Model:                            3
Date:                Wed, 21 Jun 2023   Pseudo R-squ.:                  0.1987
Time:                        10:25:48   Log-Likelihood:                -304.49
converged:                       True   LL-Null:                       -380.02
Covariance Type:            nonrobust   LLR p-value:                 1.557e-32
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Glucose           0.0365      0.004      9.561      0.000       0.029       0.044
BloodPressure    -0.0059      0.005     -1.227      0.220      -0.015       0.004
Age               0.0230      0.008     

# glucose and age will tell you if you have diabetes or not

- bp goes up, chances of sugar will decrease




In [29]:
pred_y = mod1.predict(x_test)

In [30]:
x_test =sm.add_constant(x_test,prepend=False)

In [31]:
pred_y[1:5] #prob of 0 and 1

102    0.270104
543    0.086141
146    0.051213
97     0.065689
dtype: float64

In [32]:
y_test[:5]

647    1
102    0
543    0
146    0
97     0
Name: Outcome, dtype: int64

In [33]:
res=[]

In [34]:
res[:5]

[]

In [35]:
for ctr in pred_y:
   if ctr<0.5:
    res.append(0)
   else:
    res.append(1)

In [36]:
res[:5]

[1, 0, 0, 0, 0]

In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
confusion_matrix(y_test,res)

array([[125,  13],
       [ 28,  26]], dtype=int64)

In [39]:
from sklearn.metrics import classification_report

In [40]:
print(classification_report(y_test,res))

              precision    recall  f1-score   support

           0       0.82      0.91      0.86       138
           1       0.67      0.48      0.56        54

    accuracy                           0.79       192
   macro avg       0.74      0.69      0.71       192
weighted avg       0.77      0.79      0.77       192



In [41]:
26/(26+13)

0.6666666666666666

In [42]:
26/(26+28)

0.48148148148148145

In [43]:
0.67*0.48*2/(0.67+0.48)

0.559304347826087

In [44]:
(125+26)/(125+26+13+28)

0.7864583333333334

In [ ]:
(0.91)

# Nominal Regression

In [73]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='nominal')

In [74]:
df.head()

ses  write  math  prog
0    1     35    41     1
1    2     33    41     2
2    3     39    44     3
3    1     37    42     1
4    2     31    40     2

In [75]:
df = df.drop('write',axis=1) #removing 'write' column
f.head()

ses  math  prog
0    1    41     1
1    2    41     2
2    3    44     3
3    1    42     1
4    2    40     2

In [76]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('prog',axis=1),df['prog'],test_size=0.25)

In [77]:
ses_dummy=pd.get_dummies(df['ses'],drop_first=True)

In [78]:
df=df.drop('ses',axis=1)

In [79]:
df=pd.concat([df,ses_dummy],axis=1)
df.head()

math  prog  2  3
0    41     1  0  0
1    41     2  1  0
2    44     3  0  1
3    42     1  0  0
4    40     2  1  0

In [80]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('prog',axis=1),df['prog'],test_size=0.25)

In [81]:
x_train = sm.add_constant(x_train,prepend=False)

In [82]:
mod1=sm.MNLogit(y_train,x_train).fit()

         Current function value: 0.676978
         Iterations: 35


C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


In [83]:
print(mod1.summary())

                          MNLogit Regression Results                          
Dep. Variable:                   prog   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      142
Method:                           MLE   Df Model:                            6
Date:                Wed, 21 Jun 2023   Pseudo R-squ.:                  0.3414
Time:                        12:20:13   Log-Likelihood:                -101.55
converged:                      False   LL-Null:                       -154.19
Covariance Type:            nonrobust   LLR p-value:                 1.971e-20
    prog=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
math          -0.0164      0.032     -0.506      0.613      -0.080       0.047
2              2.5554      0.596      4.286      0.000       1.387       3.724
3             40.1285   2.19e+07   1.83e-06      1.0

In [85]:
x_train.head()

math  2  3  const
72     51  0  1    1.0
66     45  0  0    1.0
151    56  0  1    1.0
186    64  0  1    1.0
113    57  1  0    1.0

In [89]:
mydata = pd.DataFrame([[70,0,0,1],[70,1,0,1],[70,0,1,1]],columns = ['math','2','3','const'])

In [90]:
mydata

math  2  3  const
0    70  0  0      1
1    70  1  0      1
2    70  0  1      1

In [91]:
mod1.predict(mydata)

0         1         2
0  5.143690e-01  0.231632  0.253999
1  2.807212e-02  0.162779  0.809149
2  2.577239e-19  0.031065  0.968935

In [92]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='VIF')
df.head()

Education  Region  Gender  Exp  Union   Wage  Age  Race  Occupation  \
0          9       0       1   42      0   4.95   57     3           6   
1         12       0       0    1      0   6.67   19     3           6   
2         12       0       0    4      0   4.00   22     3           6   
3         12       0       0   17      0   7.50   35     3           6   
4         13       0       0    9      1  13.07   28     3           6   

   Sector  Married  
0       1        1  
1       1        0  
2       0        0  
3       0        1  
4       0        0

In [93]:
df.columns

Index(['Education', 'Region', 'Gender', 'Exp', 'Union', 'Wage', 'Age', 'Race',
       'Occupation', 'Sector', 'Married'],
      dtype='object')

In [95]:
df = df[['Education','Gender','Exp','Age','Wage']]

In [97]:
gd_dummy = pd.get_dummies(df['Gender'],drop_first=True)

In [100]:
df = df.drop('Gender',axis=1)

In [101]:
df = pd.concat([df,gd_dummy],axis=1)

In [102]:
df.head()

Education  Exp  Age   Wage  1
0          9   42   57   4.95  1
1         12    1   19   6.67  0
2         12    4   22   4.00  0
3         12   17   35   7.50  0
4         13    9   28  13.07  0

In [103]:
x_train = df.drop('Wage',axis=1)

In [104]:
y_train = df['Wage']

In [105]:
mod1 = sm.OLS(y_train,x_train).fit()

In [106]:
print(mod1.summary())

                                 OLS Regression Results                                
Dep. Variable:                   Wage   R-squared (uncentered):                   0.817
Model:                            OLS   Adj. R-squared (uncentered):              0.816
Method:                 Least Squares   F-statistic:                              591.8
Date:                Wed, 21 Jun 2023   Prob (F-statistic):                   1.10e-193
Time:                        16:45:00   Log-Likelihood:                         -1550.9
No. Observations:                 533   AIC:                                      3110.
Df Residuals:                     529   BIC:                                      3127.
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [107]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [108]:
variance_inflation_factor(df.values,0) #column number 0 is Education

368.9046844691842

In [109]:
variance_inflation_factor(df.values,1) #column number 1 is Experience

544.6987999131815

In [110]:
variance_inflation_factor(df.values,2) #column number 2 is Age

1562.7050138396557

- If the VIF value is single digit 0 to 10 then no action is needed.
- If VIF value is between 10-20 then also ignore.
- But VIF value above 20-25, you need to take action

In [2]:
import mord

In [5]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ordinal')
df.head()

Survival  Region  ToxicLevel
0         1       1        62.0
1         1       2        46.0
2         2       1        48.5
3         3       2        32.0
4         2       1        63.5

In [6]:
from mord import LogisticAT

In [8]:
reg_dummy = pd.get_dummies(df['Region'],drop_first=True)

In [9]:
df = df.drop('Region',axis=1)

In [10]:
df = pd.concat([df,reg_dummy],axis=1)

In [11]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survival',axis=1),df['Survival'],test_size=0.25)

In [12]:
x_train = sm.add_constant(x_train,prepend=False)

In [13]:
mod1 = LogisticAT().fit(x_train,y_train)

In [14]:
x_test = sm.add_constant(x_test,prepend=False)

In [15]:
pred_y = mod1.predict(x_test)

In [16]:
print(confusion_matrix(y_test,pred_y))

[[ 1  3  0]
 [ 1 10  0]
 [ 0  4  0]]


In [ ]:
10/(10+n+n)

# Count model

- poisson regression
- response is discrete with less variation
- 

In [17]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='poisson')
df.head()

num_awards  prog  math
0           0     3    41
1           0     1    41
2           0     3    44
3           0     3    42
4           0     3    40

In [18]:
prog_dummy = pd.get_dummies(df['prog'],drop_first=True)

In [19]:
df = df.drop('prog',axis=1)

In [20]:
df = pd.concat([df,prog_dummy],axis=1)

In [21]:
df.head()

num_awards  math  2  3
0           0    41  0  1
1           0    41  0  0
2           0    44  0  1
3           0    42  0  1
4           0    40  0  1

In [30]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(['num_awards'],axis=1),(df['num_awards'], test_size = 0.25)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3536277732.py, line 1)

In [ ]:
x_train = sm.add_constant(x_train,prepend=False)

In [26]:
from statsmodels.discrete.discrete_model import Poisson as psn

In [ ]:
df_train = pd.concat([x_train,y_train],axis=1)

In [ ]:
df_train.head()

In [ ]:
mod1 = psn.from_formula('num_awards ~ math + 2 + 3',data=df_train)

Null hypothesis for prog2 -
when you move from prog 1 to prog 2 the number of job offers are same